# Generated by Django 3.2.4 on 2021-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='Current_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='Voltage_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
